### ISSUE TITLE
此处7.3已经不兼容了

### ISSUE THREAD

**Issue by ken678** [ITwuzhiwei/getImgSrc#2]
https://github.com/ITzhiwei/getImgSrc/blob/f555dd6ec9ad02a4f8cb4b89b20ee50b49bdc906/imgSrc/GetImgSrc.php#L163
$blacklist此处应该强制转成字符串或者先判断是否false

**Comment by ITzhiwei** [comment]
感谢反馈，PHP >= 8.0 后 strpos 第二参数仅支持字符串了
